---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Wildlife clearances post 2014

Code to clean wildlife clearances.

```{r}
# read data
wildlife_post_2014 <- read_lines("Data/wildlife_clearance/wildlife_clearance_data.csv")

# split on commas
wildlife_post_2014 <- str_split(wildlife_post_2014, ",|\t")

# good data separated
good_data <- wildlife_post_2014 %>% 
  keep(function(x) {
    length(x) == 8
  })

# copied from online
data_names <- c("Proposal No.", "State Name",
                "Proposal Name",	"Category",
                "User Agency Name",	"Area (ha.)",
                "Proposal Status",	"Proposal received on Wildlife Warden")
```

Deal with bad data.

```{r}
# process bad data
bad_data <- wildlife_post_2014 %>% 
  discard(function(x) {
    length(x) == 8
  })

# remove excess length
bad_data <- map(bad_data, function(x) {
  x[1:10] %>% 
    # drop where ""
    discard(is.na) %>% 
    discard(.p = function(p) {
      p == ""
    })
})

# check which are good now
fixed_bad_data <- bad_data %>% 
  keep(function(x) {
    length(x) == 8
  })

bad_data <- bad_data %>% 
  discard(function(x) {
    length(x) == 8
  })

# set names
good_data <- map(append(good_data, fixed_bad_data), function(x) {
  x %>% set_names(data_names)
})

# make tibble
good_data <- bind_rows(good_data)
```

More fixing bad data.

```{r}
# which states
states <- good_data$`State Name` %>% unique()
types <- good_data$Category %>% unique()
status <- good_data$`Proposal Status` %>% 
  unique()

# subset for numerics
status <- str_subset(status, "\\d", negate = T)
types <- str_subset(types, "\\d", negate = T)

# make tibbles by rescuing data
# wildlife_post_2014 <- 
fixed_bad_data_2 <- bad_data %>% 
  compact() %>% 
  map(function(x) {
    state <- x[[2]]
    area <- map(x, as.numeric) %>% 
      discard(is.na) %>% 
      unlist() %>% 
      last()
    x <- str_flatten(x, collapse = " ")
    category <- str_match(x, types) %>% 
      discard(is.na)
    status <- str_match(x, status) %>% 
      discard(is.na)
    
    if(is.null(area)) {
      area <- 0
    }
    
    list(state_name = state, 
         category = category, 
         proposal_status = status, 
         area_applied = area)
  })

# determine length after compacting
fixed_bad_data_2 <- map(fixed_bad_data_2, compact) %>% 
  keep(function(x) {
    length(x) == 4
  })

fixed_bad_data_2 <- bind_rows(fixed_bad_data_2)


# set column names
colnames(good_data) <- str_to_lower(colnames(good_data)) %>% 
  str_replace_all(" ", "_")

# rename area
good_data <- rename(good_data,
                    area_applied = `area_(ha.)`)

# convert class
good_data <- mutate(good_data,
                    area_applied = as.numeric(area_applied))

# bind rows
wildlife_post_2014 <- bind_rows(good_data, fixed_bad_data_2)
```

```{r}
# export data
write_csv(wildlife_post_2014,
          path = "Data/wildlife_clearance/wildlife_clearance_data_post_2014.csv")
```

